#!/bin/bash

source venv/bin/activate

# args="--server.runOnSave true --logger.level debug"
args="--server.runOnSave true --logger.level warning"

export DEBUG=true
streamlit run $args run_streamlit.py
